spring.application.name=springboot-blog-rest-api
spring.datasource.url=jdbc:mysql://localhost:3306/myblog
server.port=8081
spring.datasource.username=root
spring.datasource.password=ggAbdo123
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false